# Generated by Django 4.2.16 on 2024-10-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='banner_Image',
            new_name='banner_image',
        ),
    ]
